language: node_js
nodejs:
  - stable
branches:
  only:
    - master
script: 
  - npm run build
#   - npm run lint
#   - npm test    
env:
  global:
    - REMOTE_PATH=Uploads
    - REMOTE_USER=deploy
    - REMOTE_HOST=167.172.168.233
before_install:
  - bash scripts/install.sh
after_success:
  - bash scripts/deploy.sh
