language: node_js
nodejs:
  - stable
jobs:
  include:
    - stage: Unit Tests      
      script: npm test
    - stage: Build
      script: npm run build
    - stage: Deploy
      before_install: bash scripts/install.sh
      env:
        - REMOTE_PATH=Uploads
        - REMOTE_USER=deploy
        - REMOTE_HOST=167.172.168.233
      script: bash scripts/deploy.sh 
stages:
  - name: Unit Tests
  - name: Build
  - name: Deploy
    if: branch = master AND type = push
